### ISSUE TITLE
AlwaysSpawn affected by sleep from SoundJoin?

### ISSUE THREAD

**Issue by SalmonGER** [SalmonCraftPE/SCraftPE-MH#10]
Looks like the commit which fixed SoundJoin also delays AlwaysSpawn. It isn't critical or something but it would be nice to fix it.

**Comment by Aericio** [comment]
Means SoundJoin runs first and AlwaysSpawn runs after?

**Comment by SalmonGER** [comment]
It seems like sleep in SoundJoin affects AlwaysSpawn

**Comment by SalmonGER** [comment]
Also that sleep delay is needed because SoundJoin sends the sound when the player joins and not when he joined. So you are meant to listen to it while you're still joining. I don't know if the original plugin works since it's for BukkitPE but for ClearSky it doesn't without changes. 
Well, that's what I learned.

**Comment by SalmonGER** [comment]
Fixed I think. Doesn't occur anymore.
